create schema if not exists mock;
create schema if not exists dwh;


create table if not exists mock.mock_data (
	id 					 int,
	customer_first_name	 varchar(100),
	customer_last_name 	 varchar(100),
	customer_age         int,
	customer_email       varchar(100),
	customer_country     varchar(100),
	customer_postal_code varchar(50),
	customer_pet_type    varchar(50),
	customer_pet_name    varchar(100),
	customer_pet_breed   varchar(50),
	seller_first_name    varchar(100),
	seller_last_name     varchar(100),
	seller_email         varchar(100),
	seller_country       varchar(100),
	seller_postal_code   varchar(50),
	product_name         varchar(50),
	product_category     varchar(50),
	product_price        numeric(10, 2),
	product_quantity     int,
	sale_date            varchar(30),
	sale_customer_id     int,
	sale_seller_id       int,
	sale_product_id      int,
	sale_quantity        int,
	sale_total_price     numeric(10, 2),
	store_name           varchar(100),
	store_location       varchar(100),
	store_city           varchar(100),
	store_state          varchar(100),
	store_country        varchar(100),
	store_phone          varchar(50),
	store_email          varchar(100),
	pet_category         varchar(50),
	product_weight       numeric(10, 2),
	product_color        varchar(50),
	product_size         varchar(50),
	product_brand        varchar(100),
	product_material     varchar(100),
	product_description  text,
	product_rating       real,
	product_reviews      int,
	product_release_date varchar(30),
	product_expiry_date  varchar(30),
	supplier_name        varchar(100),
	supplier_contact     varchar(100),
	supplier_email       varchar(100),
	supplier_phone       varchar(50),
	supplier_address     varchar(100),
	supplier_city        varchar(100),
	supplier_country     varchar(100)
);


