copy mock.mock_data from '/data/MOCK_DATA.csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (1).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (2).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (3).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (4).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (5).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (6).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (7).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (8).csv' with (FORMAT CSV, HEADER TRUE);
copy mock.mock_data from '/data/MOCK_DATA (9).csv' with (FORMAT CSV, HEADER TRUE);